# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-12 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_status', models.IntegerField()),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('comment', models.CharField(max_length=2048)),
            ],
        ),
    ]
