# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ie', '0002_auto_20180512_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_area', models.CharField(max_length=100)),
                ('picture_area', models.BinaryField()),
                ('description_area', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_equip', models.CharField(max_length=50)),
                ('station_number', models.IntegerField()),
                ('picture_equip', models.BinaryField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hole.Area')),
                ('ie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ie.Ie')),
            ],
        ),
    ]
